feat: add cart page

diff --git a/.github/workflows/docker-build.yml b/.github/workflows/docker-build.yml
--- a/.github/workflows/docker-build.yml
+++ b/.github/workflows/docker-build.yml
@@ -1,42 +1,42 @@
-name: Build and Push Docker Image on PR Close
+# name: Build and Push Docker Image on PR Close
 
-on:
-  pull_request:
-    types: [closed]
+# on:
+#   pull_request:
+#     types: [closed]
 
-jobs:
-  build-and-push:
-    runs-on: ubuntu-latest
+# jobs:
+#   build-and-push:
+#     runs-on: ubuntu-latest
 
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
-        with:
-          fetch-depth: 0  # Trae todo el historial de commits
+#     steps:
+#       - name: Checkout repository
+#         uses: actions/checkout@v4
+#         with:
+#           fetch-depth: 0  # Trae todo el historial de commits
 
-      - name: Verify files
-        run: |
-          ls -la
-          if [ ! -f "Dockerfile" ]; then
-            echo "ERROR: Dockerfile not found!"
-            exit 1
-          fi
+#       - name: Verify files
+#         run: |
+#           ls -la
+#           if [ ! -f "Dockerfile" ]; then
+#             echo "ERROR: Dockerfile not found!"
+#             exit 1
+#           fi
 
-      - name: Set up Docker Buildx
-        uses: docker/setup-buildx-action@v3
+#       - name: Set up Docker Buildx
+#         uses: docker/setup-buildx-action@v3
 
-      - name: Login to Docker Hub
-        uses: docker/login-action@v3
-        with:
-          username: ${{ secrets.DOCKER_USERNAME }}
-          password: ${{ secrets.DOCKER_PASSWORD }}
+#       - name: Login to Docker Hub
+#         uses: docker/login-action@v3
+#         with:
+#           username: ${{ secrets.DOCKER_USERNAME }}
+#           password: ${{ secrets.DOCKER_PASSWORD }}
 
-      - name: Build and push Docker image
-        uses: docker/build-push-action@v5
-        with:
-          context: .
-          file: ./Dockerfile  # Especifica explícitamente la ruta
-          push: true
-          tags: |
-            joseluiscodesk8/nombre-app:latest
-            joseluiscodesk8/nombre-app:${{ github.sha }}
+#       - name: Build and push Docker image
+#         uses: docker/build-push-action@v5
+#         with:
+#           context: .
+#           file: ./Dockerfile  # Especifica explícitamente la ruta
+#           push: true
+#           tags: |
+#             joseluiscodesk8/nombre-app:latest
+#             joseluiscodesk8/nombre-app:${{ github.sha }}
